import mongoose from 'mongoose';
const { Schema, model } = mongoose;

const ref = { type: Schema.Types.ObjectId, required: true };
export const Buyer = model('Buyer', new Schema({ name: { type: String, required: true }, mobile: { type: String, unique: true, required: true }, passwordHash: { type: String, required: true, select: false }, location: String, verified: { type: String, enum: ['PENDING', 'VERIFIED', 'REJECTED', 'SUSPENDED'], default: 'PENDING' }, role: { type: String, default: 'buyer' } }, { timestamps: true }));
export const BuyerVerification = model('BuyerVerification', new Schema({ buyer: ref, status: { type: String, enum: ['PENDING', 'VERIFIED', 'REJECTED', 'SUSPENDED'], default: 'PENDING' }, documents: [String], reviewedAt: Date }, { timestamps: true }));
export const DemandRequirement = model('DemandRequirement', new Schema({ buyer: ref, crop: String, variety: String, quantity: Number, unit: String, quality: String, targetPrice: Number, maxPrice: Number, location: String, radius: Number, requiredBy: Date, additionalRequirements: String, status: { type: String, default: 'OPEN' } }, { timestamps: true }));
export const FarmerListing = model('FarmerListing', new Schema({ farmer: ref, crop: String, variety: String, quantity: Number, unit: String, quality: String, price: Number, location: String, distanceKm: Number, availableFrom: Date, availability: String, verified: Boolean, smallFarmer: Boolean, rating: Number, active: { type: Boolean, default: true } }, { timestamps: true }));
export const Match = model('Match', new Schema({ demand: ref, listing: ref, score: Number, reasons: [String] }, { timestamps: true }));
export const Offer = model('Offer', new Schema({ buyer: ref, farmer: ref, listing: ref, demand: ref, parent: { type: Schema.Types.ObjectId, ref: 'Offer' }, quantity: Number, price: Number, note: String, state: { type: String, enum: ['PENDING', 'COUNTERED', 'ACCEPTED', 'REJECTED', 'WITHDRAWN'], default: 'PENDING' } }, { timestamps: true }));
export const Conversation = model('Conversation', new Schema({ buyer: ref, farmer: ref, listing: ref, demand: ref, offer: { type: Schema.Types.ObjectId, ref: 'Offer' } }, { timestamps: true }));
export const Message = model('Message', new Schema({ conversation: ref, sender: ref, senderRole: { type: String, enum: ['buyer', 'farmer'] }, text: String, event: { type: String, enum: ['TEXT', 'OFFER', 'COUNTER', 'ACCEPTED', 'REJECTED'], default: 'TEXT' }, offer: { type: Schema.Types.ObjectId, ref: 'Offer' } }, { timestamps: true }));
export const BuyerRating = model('BuyerRating', new Schema({ buyer: ref, farmer: ref, deal: ref, overall: Number, paymentReliability: Number, communication: Number, agreementReliability: Number, note: String }, { timestamps: true }));
export const Deal = model('Deal', new Schema({ buyer: ref, farmer: ref, listing: ref, demand: ref, offer: ref, status: { type: String, enum: ['ACTIVE', 'COMPLETED', 'CANCELLED'], default: 'ACTIVE' } }, { timestamps: true }));
